In [6]:
import numpy as np
import cudaq_qec as qec
steane = qec.get_code("steane")

In [8]:
Hz = steane.get_parity_z()
print(f"Hz:\n{Hz}")
observable = steane.get_observables_z()
print(f"observable:\n{observable}")

# error probabily
p = 0.1
# Get a decoder
decoder = qec.get_decoder("single_error_lut", Hz)

# Perform a code capacity noise model numerical experiment
nShots = 10
nLogicalErrors = 0
for i in range(nShots):
    print(f"shot: {i}")

    # Generate noisy data
    data = qec.generate_random_bit_flips(Hz.shape[1], p)
    print(f"data: {data}")

    # Calculate which syndromes are flagged.
    syndrome = Hz @ data % 2
    print(f"syndrome: {syndrome}")

    # Decode the syndrome to predict what happened to the data
    results = decoder.decode(syndrome)
    convergence = results.converged
    result = results.result
    data_prediction = np.array(result, dtype=np.uint8)
    print(f"data_prediction: {data_prediction}")

    # See if this prediction flipped the observable
    predicted_observable = observable @ data_prediction % 2
    print(f"predicted_observable: {predicted_observable}")

    # See if the observable was actually flipped
    actual_observable = observable @ data % 2
    print(f"actual_observable: {actual_observable}")
    if (predicted_observable != actual_observable):
        nLogicalErrors += 1

Hz:
[[1 1 1 1 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 1 1 0 1 1]]
observable:
[[0 0 0 0 1 1 1]]
shot: 0
data: [0 0 0 0 0 0 0]
syndrome: [0 0 0]
data_prediction: [0 0 0 0 0 0 0]
predicted_observable: [0]
actual_observable: [0]
shot: 1
data: [0 0 0 0 0 0 0]
syndrome: [0 0 0]
data_prediction: [0 0 0 0 0 0 0]
predicted_observable: [0]
actual_observable: [0]
shot: 2
data: [1 1 0 0 0 0 0]
syndrome: [0 1 0]
data_prediction: [0 0 0 0 1 0 0]
predicted_observable: [1]
actual_observable: [0]
shot: 3
data: [0 0 0 0 0 0 0]
syndrome: [0 0 0]
data_prediction: [0 0 0 0 0 0 0]
predicted_observable: [0]
actual_observable: [0]
shot: 4
data: [0 0 0 0 0 0 1]
syndrome: [0 0 1]
data_prediction: [0 0 0 0 0 0 1]
predicted_observable: [1]
actual_observable: [1]
shot: 5
data: [0 1 0 0 0 1 0]
syndrome: [1 0 1]
data_prediction: [0 0 0 1 0 0 0]
predicted_observable: [0]
actual_observable: [1]
shot: 6
data: [0 0 0 0 0 0 0]
syndrome: [0 0 0]
data_prediction: [0 0 0 0 0 0 0]
predicted_observable: [0]
actual_observable: [0]
shot

In [9]:
# Count how many shots the decoder failed to correct the errors
print(f"{nLogicalErrors} logical errors in {nShots} shots\n")

# Can also generate syndromes and data from a single line with:
syndromes, data = qec.sample_code_capacity(Hz, nShots, p)
print("From sample function:")
print("syndromes:\n", syndromes)
print("data:\n", data)

2 logical errors in 10 shots

From sample function:
syndromes:
 [[0 0 0]
 [0 0 0]
 [0 0 1]
 [1 0 1]
 [0 1 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [1 1 0]]
data:
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]
 [1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0]]
